title = "Ryan Rampersad"
baseurl = "https://ryanrampersad.com/"
languageCode = "en-us"

googleAnalytics = "UA-18192523-1"

[params]
  description = "Ryan Rampersad is a software engineer, web developer, consultant, podcaster and technology enthusiast."
  keywords = "ryan rampersad, software engineer, web developer, consultant, java, php, javascript, rust, go, compilers, enthusiast, podcast"
  author = "Ryan Rampersad"
