title = "Ryan Rampersad"
baseurl = "http://ryanrampersad.com/"
languageCode = "en-us"

[params]
  description = "Ryan Rampersad is a software engineer, web developer, podcaster and technology enthusiast."
  keywords = "ryan rampersad, software engineer, web developer, php, javascript, rust, go, compilers, enthusiast, podcast"
  author = "Ryan Rampersad"
